# Generated by Django 4.0.3 on 2022-04-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('liga', models.CharField(max_length=50)),
                ('dataDoJogo', models.DateField()),
                ('hora', models.TimeField()),
                ('nomeTime1', models.CharField(max_length=30)),
                ('nomeTime2', models.CharField(max_length=30)),
                ('golsTime1', models.IntegerField()),
                ('golsTime2', models.IntegerField()),
                ('escudoTime1', models.URLField()),
                ('escudoTime2', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
