# Generated by Django 4.0.3 on 2022-04-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brasileirao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
