# Generated by Django 4.0.3 on 2022-04-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brasileirao', '0002_alter_jogo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogo',
            options={'ordering': ['id'], 'verbose_name': 'Jogo', 'verbose_name_plural': 'Jogos'},
        ),
    ]
